name: Docker Image CI

on: [push]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        name: checkout

      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '3.1.100' # SDK Version to use.
      - run: dotnet build --configuration Release

      - name: dotnet publish
        run: |
          dotnet publish -c Release -o ${{env.DOTNET_ROOT}}/src 
      - uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.DOCKER_CONTAINNER_REGISTRY }}
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - run: |
          docker build  --file Dockerfile --tag ${{ secrets.DOCKER_CONTAINER_REGISTRY }}/${{ secrets.NOME_IMAGEM }}:$GITHUB_RUN_NUMBER
          docker push ${{ secrets.DOCKER_CONTAINNER_REGISTRY }}/src:${{ github.sha }} 
