steps:
  - uses: actions/checkout@v2
    name: checkout

  - uses: actions/setup-dotnet@v1
    with:
      dotnet-version: '3.1.100' # SDK Version to use.
  - run: dotnet build --configuration Release

  - name: dotnet publish
    run: |
      dotnet publish -c Release -o ${{env.DOTNET_ROOT}}/src 
  - uses: azure/docker-login@v1
    with:
      login-server: ${{ secrets.DOCKER_CONTAINNER_REGISTRY }}
      username: ${{ secrets.DOCKER_USERNAME }}
      password: ${{ secrets.DOCKER_PASSWORD }}

<<<<<<< HEAD
  - run: |
      docker build -t ${{ secrets.DOCKER_CONTAINNER_REGISTRY }}/src:${{ github.sha }} .
      docker push ${{ secrets.DOCKER_CONTAINNER_REGISTRY }}/src:${{ github.sha }} 
=======
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Docker Login - Azure Container Registry
      uses: Azure/docker-login@v1
      with:
        login-server: backendjusbrasilgithubactions
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build e Push no Azure Container Registry
      run: |
        docker build . --file Dockerfile --tag ${{ secrets.DOCKER_CONTAINER_REGISTRY }}/${{ secrets.NOME_IMAGEM }}:$GITHUB_RUN_NUMBER
        docker tag ${{ secrets.DOCKER_CONTAINER_REGISTRY }}/${{ secrets.NOME_IMAGEM }}:$GITHUB_RUN_NUMBER ${{ secrets.DOCKER_CONTAINER_REGISTRY }}/${{ secrets.NOME_IMAGEM }}:latest
        docker push ${{ secrets.DOCKER_CONTAINER_REGISTRY }}/${{ secrets.NOME_IMAGEM }}
>>>>>>> da47d6f66037d83ff08d5534c46fecd778665a97
